import { SDLayoutOS } from "../../typings";
import Command from "../classes/Command";
const images = {
    "macos":{
      "correct":"https://cdn.discordapp.com/attachments/649724928542900264/830211676355559424/correct_sd.png",
      "incorrect":"https://cdn.discordapp.com/attachments/649724928542900264/830211690813063208/incorrect_sd.png"
    },
    "win":{
      "correct":"https://cdn.discordapp.com/attachments/710631969993654334/933903765159948389/good_win11.png",
      "incorrect":"https://cdn.discordapp.com/attachments/710631969993654334/933903765378060298/bad_win11.png"
    }
}

export default new Command({
  commandName:"sd",
  subCommandGroup:"switch",
    execute(interaction){
          let os:SDLayoutOS = (interaction.options.getString("os", false)?.toString() || "win") as SDLayoutOS;
          let symptoms = [`Missing lp0 lib`, `Missing or old minerva lib`, `Update bootloader`, `Missing pkg1`, `Text-based version of hekate`]
          interaction.reply({
              content:`If you're getting experiencing one of the following:\n${symptoms.map(s => `*${s}*`).join("\n")}\n\nYour SD card layout may be incorrect. Please confirm that you **extracted** the contents of the \`sd\` folder onto your SD card root.`,
              embeds:[
                {
                    "title":"✅ Correct Layout",
                    "image":{
                      "url":`${images[os].correct}`
                    }
                },
                {
                    "title":"❌ Incorrect Layout",
                    "image":{
                      "url":`${images[os].incorrect}`
                    },
                },
                {
                  description:`**Note:** \`Nintendo\` folder is autogenerated by the Nintendo Switch and does not need to be created manually.`
                }
              ]
          })
    }
})